# file: jupyter_config.yaml

jupyterhub:
  singleuser:
    cmd: ['start-singleuser.sh']
    startTimeout: 600
    extraEnv:
      EXTRA_PIP_PACKAGES: >-
      GCSFUSE_BUCKET: pangeo-data
    storage:
      type: dynamic
      capacity: 10G
      dynamic:
        storageClass: manila-cephfs-share-ond
      #extraVolumes:
      #  - name: fuse
      #    hostPath:
      #      path: /dev/fuse
      #extraVolumeMounts:
      #  - name: fuse
      #    mountPath: /dev/fuse
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G

  hub:
    db:
      type: sqlite-pvc
      pvc:
        accessModes:
          - ReadWriteMany
        storage: 1G
        storageClassName: manila-cephfs-share-ond
    extraConfig:
      customPodHook: |
        from kubernetes import client
        def modify_pod_hook(spawner, pod):
            pod.spec.containers[0].security_context = client.V1SecurityContext(
                privileged=True,
                capabilities=client.V1Capabilities(
                    add=['SYS_ADMIN']
                )
            )
            return pod
        c.KubeSpawner.modify_pod_hook = modify_pod_hook
        c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/custom/images/logo.png'
        c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/',
                                      '/usr/local/share/jupyterhub/templates/']
    image:
      name: jupyterhub/k8s-hub
      tag: 0.7.0 #v0.6
      - name: custom-templates
        gitRepo:
          repository: "https://github.com/pangeo-data/pangeo-custom-jupyterhub-templates.git"
          revision: "da496d24ec603a0b5f9932bfeae40594e8dff5a4"
    extraVolumeMounts:
      - mountPath: /usr/local/share/jupyterhub/custom_templates
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/templates"
      - mountPath: /usr/local/share/jupyterhub/static/custom
        name: custom-templates
        subPath: "pangeo-custom-jupyterhub-templates/assets"

  cull:
    enabled: true
    users: false
    timeout: 1200
    every: 600

  # this section specifies the IP address for pangeo.pydata.org
  # remove or change for a custom cluster
  proxy:
    service:
      annotations:
        service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
      type: LoadBalancer
      #loadBalancerIP: 10.60.253.65
      #type: NodePort
      #nodePorts:
      #  http: 32000
