# file: secret_config.yaml

jupyterhub:
  proxy:
    secretToken: 8ab358498cadf3e05db75341c3ba9b41d65e565433a6ec17020afe31f2dd7806

  # comment this out if not using github authentication
  auth:
    type: github
    github:
      clientId: 8254cef9ddda063f54a7
      clientSecret: 361ce236c7b86b76b1715e4971cc06de25508d26
      callbackUrl: "http://10.60.253.13:32000/hub/oauth_callback"
    admin:
      access: true
      users:
        - brtknr
